### ISSUE TITLE
Add any issues with the ISOC beta site here

### ISSUE THREAD

**Issue by danyork** [InternetSociety/web-site-feedback#1]
Please use the "New issue" button to submit feedback about the beta site.

**Comment by acalderon** [comment]
Hi Dan:

As a frequent user of the ISOC website, I can truly say that this is a huge improvement. It has a logical and user-friendly way to navigate and access desired information.  It decreases the "guessing factor" of where could the desired information be located. I appreciate the fact that on the landing page you can even see an area where "live streaming can be accessed".

What happens if more than one "live event" is taking place? Is this "live event" referring to those taking place at ISOC headquarters or intended for global membership?

The fact that the information of each section is clean, easy to read and goes to the point helps a lot to get the message across. Thus, given the younger audience an immediate idea of what the section contains. I am assuming that the "News Section" will always reflect the latest events/news submitted by "categories" to simplify searches in the "Old News" repository.

Great job!

**Comment by danyork** [comment]
@acalderon - My sincere apologies!  I didn't realize that your comment had been left on this issue!

As you can see on the new site - https://www.internetsociety.org/ - the News section does show the latest events/news.

As far as the live events - the idea with the home page is that we can focus on TWO items on the top "hero" are. We used this a great deal during the InterCommunity event last week, pointing to live events and other information.  We did, in fact, point to two different live events at the same time.

As to your "ISOC headquarters vs global membership"... I have a longer term vision where I want to be incorporating more visibility of Chapter / SIG activities into the main site.  The first step was to launch the site!  Now we can start looking at what comes next.

Thanks for your kind words. I am going to close this particular "issue" on Github. If you do have any feedback about the new site, please feel free to open a new issue at:

https://github.com/InternetSociety/web-site-feedback/issues

Thanks again for the initial feedback - and I apologize for somehow missing that the comment had been left.
