### ISSUE TITLE
Trustee's Committee Pages

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#14]
On the Trustee [pages](https://www.internetsociety.org/board-of-trustees/), it shows the committees that we're on.  But, it doesn't show historical data so for example if you go back to 2014-15 it shows the committees we're on now.

**Comment by danyork** [comment]
Thanks, Sean.  Yes, we've identified this as an issue. It involves a bit of complexity (you can imagine the series of database tables) and so the fix will take us a bit. But yes, this needs to be fixed.

**Comment by danyork** [comment]
Sean, just an update to say that this is not a forgotten issue. We're still working through some ideas about how to do this in a way that doesn't cause a performance impact.

**Comment by danyork** [comment]
@seanturner - I've got some great news! We found a different way to do this so that we didn't impact performance. We've now gone back all the way to 1992 and updated all the pages with the lists of committees they were on in that year.  You can see that all here:

https://www.internetsociety.org/board-of-trustees/

Just choose the year from the drop-down and you'll see the relevant lists.

Please let me know if you see anything else... otherwise we can _finally_ close this one off!

**Comment by seanturner** [comment]
slick!  I’d consider this one closed.

spt
